version: '3'
services:
    sentinel1: 
        hostname: sentinel1
        image: vaibhav93/monitoring_icinga2:v1
        networks:
            - test_monitoring
        volumes:
            - ./etc/icinga2/objects/:/etc/icinga2/conf.d/objects
    thruk: 
        hostname: thruk
        image: vaibhav93/monitoring_thruk:v1
        networks:
            - test_monitoring
        ports: 
            - "80:80"
    client:
        hostname: client
        image: centos:7
        networks: 
            - test_monitoring
        entrypoint:
            - /bin/bash
        stdin_open: true
networks:
    test_monitoring:
        driver: "bridge"
